spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database: ${DATABASE_NAME}
    database-platform: ${DATABASE_PLATFORM}
  # data:
  #   redis:
  #     host: ${REDIS_HOST}
  #     port: ${REDIS_PORT}
  #     username: ${REDIS_USERNAME}
  #     password: ${REDIS_PASSWORD}
  #     ssl:
  #       enabled: true
